// Get users:
GET http://localhost:3003/users

### // Create users:
POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "Salem",
    "email": "salem@email.com",
    "password": "adoroficarnotelhado"
}